// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-OMoiIqRi8_UIMiuJ-rA1zSnGJH6Nxc4',
    appId: '1:936038387782:web:a66b1fc295ec0bfe857a47',
    messagingSenderId: '936038387782',
    projectId: 'mamak-565f3',
    authDomain: 'mamak-565f3.firebaseapp.com',
    storageBucket: 'mamak-565f3.appspot.com',
    measurementId: 'G-KVE3R2HZNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB--iJqrSD3UaLUaDkswDAUd5TqHpzXryw',
    appId: '1:936038387782:android:f5282ad3ad6410d6857a47',
    messagingSenderId: '936038387782',
    projectId: 'mamak-565f3',
    storageBucket: 'mamak-565f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsBpPgV3-6I2DkB0icuVPvdcSsD1yVuww',
    appId: '1:936038387782:ios:ecb692bae8198931857a47',
    messagingSenderId: '936038387782',
    projectId: 'mamak-565f3',
    storageBucket: 'mamak-565f3.appspot.com',
    iosClientId: '936038387782-cs9beo3l2e8o6vv70knt4jtq9haaom2t.apps.googleusercontent.com',
    iosBundleId: 'ir.mamakschool.mamak',
  );
}
